### ISSUE TITLE
希望能有选项在侧滑栏下方加入直接退出QQ功能

### ISSUE THREAD

**Issue by djj200504001** [zpp0196/QQSimple#4]
希望能有选项在侧滑栏内加入"直接退出QQ"这个功能，或者替换夜间模式按钮/底部天气为退出功能也行，因为有些机型是默认没有菜单键按钮的，无法通过"菜单键-退出"来直接退出QQ，如果能有这方面的支持就更方便了。

**Comment by kongphop11** [comment]
บางรุ่นมีค่าเริ่มต้นไม่มีปุ่มเมนูและไม่สามารถผ่านปุ่ม

**Comment by zpp0196** [comment]
我这几天尝试了一下最后还是没有加，需要退出用**模拟菜单按钮**功能弹出菜单退出就行了
