### ISSUE TITLE
版本2.0.1未能兼容最新的QQ版本

### ISSUE THREAD

**Issue by djj200504001** [zpp0196/QQSimple#6]
设备：HUAWEI ALP-AL00/Android 8.0.0（Oreo，API 26）
QQ版本：7.5.5（806）
QQ净化版本：2.0.1（43）
——————————————
BTW，我没找到模拟菜单按钮功能在哪……如果你是指另外装一个xposed插件的话，我找了好几个，要么需要root，要么无法在VirtualXposed里使用，对于华为这种root起来非常麻烦的机型来说，基本无解

**Comment by zpp0196** [comment]
其他功能-模拟菜单按钮
